//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessAdminWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int ID { get; set; }
        public Nullable<int> PlayerOneID { get; set; }
        public Nullable<int> PlayerTwoID { get; set; }
        public Nullable<System.DateTime> GameDateTime { get; set; }
        public Nullable<int> WinnerID { get; set; }
        public Nullable<bool> IsDraw { get; set; }
        public Nullable<int> PlayerOneCurrentRank { get; set; }
        public Nullable<int> PlayerTwoCurrentRank { get; set; }
        public Nullable<int> PlayerOneRankAfterGame { get; set; }
        public Nullable<int> PlayerTwoRankAfterGame { get; set; }
    }
}
