//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessAdminWebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int ID { get; set; }
        public int PlayerOneID { get; set; }
        public int PlayerTwoID { get; set; }
        public System.DateTime GameDate { get; set; }
        public Nullable<int> WinnerID { get; set; }
        public bool IsDraw { get; set; }
        public Nullable<int> PlayerOneCurrentRank { get; set; }
        public Nullable<int> PlayerTwoCurrentRank { get; set; }
        public Nullable<int> PlayerOneRankAfterGame { get; set; }
        public Nullable<int> PlayerTwoRankAfterGame { get; set; }
        public System.TimeSpan GameTime { get; set; }
        public Nullable<System.DateTime> GameDateTime { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Member Member2 { get; set; }
    }
}
