//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessAdminWebMVC
{
    using ChessAdminWebMVC.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChessAdminDbEntities1 : DbContext, IChessAdminWebMVCContext
    {
        public ChessAdminDbEntities1()
            : base("name=ChessAdminDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        void IChessAdminWebMVCContext.MarkAsModified(Game item)
        {
            
        }

        void IChessAdminWebMVCContext.MarkAsModified(Member item)
        {
            
        }

        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
